"""make textbook_sources.note_id nullable

Revision ID: 50495fd1b0b6
Revises: 1cd1e82c694a
Create Date: 2026-04-16 23:36:17.137150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50495fd1b0b6'
down_revision: Union[str, Sequence[str], None] = '1cd1e82c694a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbook_sources', 'note_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbook_sources', 'note_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
