"""iap_entitlements table

Revision ID: 588f1d04cd22
Revises: c3d4e5f6a7b8
Create Date: 2026-06-02 15:43:20.074680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588f1d04cd22'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iap_entitlements',
    sa.Column('original_transaction_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('last_notification_type', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('original_transaction_id')
    )
    op.create_index(op.f('ix_iap_entitlements_user_id'), 'iap_entitlements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iap_entitlements_user_id'), table_name='iap_entitlements')
    op.drop_table('iap_entitlements')
    # ### end Alembic commands ###
