"""ai feedback record and rating

Revision ID: f4b4ab3c2bae
Revises: fff3137aa9b9
Create Date: 2026-05-25 13:37:28.482588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4b4ab3c2bae'
down_revision: Union[str, Sequence[str], None] = 'fff3137aa9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_feedback_record',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('response_language', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('textbook_id', sa.String(), nullable=True),
    sa.Column('current_page', sa.Integer(), nullable=True),
    sa.Column('has_textbook_context', sa.Boolean(), nullable=False),
    sa.Column('prompt_context_snippet', sa.Text(), nullable=True),
    sa.Column('previous_context', sa.Text(), nullable=True),
    sa.Column('response_content', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_record_note_id'), 'ai_feedback_record', ['note_id'], unique=False)
    op.create_index(op.f('ix_ai_feedback_record_user_id'), 'ai_feedback_record', ['user_id'], unique=False)
    op.create_table('ai_feedback_rating',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('feedback_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('reason_tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('client_ts', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['ai_feedback_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_feedback_rating_feedback_id'), 'ai_feedback_rating', ['feedback_id'], unique=True)
    op.create_index(op.f('ix_ai_feedback_rating_user_id'), 'ai_feedback_rating', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_feedback_rating_user_id'), table_name='ai_feedback_rating')
    op.drop_index(op.f('ix_ai_feedback_rating_feedback_id'), table_name='ai_feedback_rating')
    op.drop_table('ai_feedback_rating')
    op.drop_index(op.f('ix_ai_feedback_record_user_id'), table_name='ai_feedback_record')
    op.drop_index(op.f('ix_ai_feedback_record_note_id'), table_name='ai_feedback_record')
    op.drop_table('ai_feedback_record')
    # ### end Alembic commands ###
